### ISSUE TITLE
Part 2 updates

### ISSUE THREAD

**Issue by abunur** [AladinWay/NetworkingExample#10]
Since this article is “part 2” and “part 1” already was using Alamofire, you should not cover how to integrate Alamofire in this article. Rather, you should put that in part one. Also, you say Carthage is the recommended way to install — according to whom? I think most likely Cocoapods is the more popular was, though it’s debatable, and also it can be installed via Swift Package Manager. Maybe it’s better to just refer to the install guide on the Alamofire github page…

**Comment by abunur** [comment]
This is a great article, Alamofire 5 beta was recently released, they haven’t yet updated the docs, and still there are no good samples online other than this series by you.
Would be great if you could update for the current beta as the article is a little over a year out of date now. Below is updated login function signature from your article, key changes:
AF replaces Alamofire
responseDecodable replaces .responseJSONDecodable
```Swift
  static func login(email: String, password: String, completion:@escaping (Result<UserCredentials>)->Void) {
    performRequest(router: Router.login(email: email, password: password), completion: completion)
    AF.request(Router.login(email: email, password: password))
      .validate(statusCode: 200..<300)
      .responseDecodable { (response: DataResponse<UserCredentials>) in
        guard response.result.isSuccess else {
          print("🥶 Error on login: \(String(describing: response.error))")
          return
        }
        completion(response.result)
    }
  }
```
Thanks again for providing this helpful resource.

**Comment by AfricanProgrammer** [comment]
class APIClient {
    static func login(email: String, password: String, completion:@escaping (Result<User>)->Void) {
        Alamofire.request(APIRouter.login(email: email, password: password))
            .responseJSONDecodable { (response: DataResponse<User>) in
                completion(response.result)
        }
    }
}

**Comment by NyashaMadzokere** [comment]
> class APIClient {
> static func login(email: String, password: String, completion:@escaping (Result)->Void) {
> Alamofire.request(APIRouter.login(email: email, password: password))
> .responseJSONDecodable { (response: DataResponse) in
> completion(response.result)
> }
> }
> }

Mine still doesnt work

**Comment by AladinWay** [comment]
Code is updated now
