### ISSUE TITLE
Generic type 'Result' specialized with too few type parameters (got 1, but expected 2)

### ISSUE THREAD

**Issue by merovic** [AladinWay/NetworkingExample#12]
I have this error in APIClient file

**Comment by NasH5169** [comment]
Hi, 

Try this: `Result<User, Error>`

**Comment by galahador** [comment]
is this working? @NasH5169

**Comment by mohamadilk** [comment]
Use AFResult instead of Result

**Comment by AladinWay** [comment]
I have pushed am update for Swift 5. This should fix your issue.
