### ISSUE TITLE
Cannot convert value of type 'Result<T>' to expected argument type 'Result<_>'

### ISSUE THREAD

**Issue by mariojimmy** [AladinWay/NetworkingExample#16]
return AF.request(route)
            .responseDecodable (decoder: decoder){ (response: DataResponse<T>) in
                completion(response.result)

**Comment by sandlinm** [comment]
If you haven't already figured this out, you need to use AF specific Result type (AFResult).

**Comment by atifsaeed14** [comment]
Just update 
            request.responseDecodable(decoder: decoder, completionHandler: { (response: **AFDataResponse**<T>) in
to
            request.responseDecodable(decoder: decoder, completionHandler: { (response: **DataResponse**<T>) in

**Comment by AladinWay** [comment]
Latest updated code should fix this
