### ISSUE TITLE
responseJSONDECODABLE missing

### ISSUE THREAD

**Issue by nomi2013** [AladinWay/NetworkingExample#2]
Showing error in APIClient.swift
Value of type 'DataRequest' has no member 'responseJSONDecodable', from below method

@discardableResult
    private static func performRequest<T:Decodable>(route:APIRouter, decoder: JSONDecoder = JSONDecoder(), completion:@escaping (Result<T>)->Void) -> DataRequest {
        return Alamofire.request(route)
            .responseJSONDecodable (decoder: decoder){ (response: DataResponse<T>) in
                completion(response.result)
        }
        
    }

**Comment by AladinWay** [comment]
Hey, are you sure that you are using the branch `alamofire5` when you have added `Alamofire` to your project ?

**Comment by nomi2013** [comment]
Thanks now working.
