### ISSUE TITLE
How response decodable DataResponse<T, Error>

### ISSUE THREAD

**Issue by gabrielmamani** [AladinWay/NetworkingExample#22]
BEFORE Alamofire 5.0.0 beta.3 works 100%
@discardableResult
    private static func performRequest<T:Decodable>(route:RequestConverterProtocol, decoder: JSONDecoder = JSONDecoder(), completion:@escaping (Result<T>)->Void) -> DataRequest {
        return AF.request(route)
            .responseDecodable (decoder: decoder){
 (response: DataResponse<T>) in
                completion(response.result)
        }
    }

AFTER Alamofire 5.0.0 beta.3 its ok?
@discardableResult
    private static func performRequest<T:Decodable>(route:RequestConverterProtocol, decoder: JSONDecoder = JSONDecoder(), completion:@escaping (Result<T, AFError>)->Void) -> DataRequest {
        return AF.request(route)
            .responseDecodable (decoder: decoder){ (response: DataResponse<T, AFError>) in
                completion(response.result)
        }
    }

<img width="942" alt="Captura de Pantalla 2020-03-01 a la(s) 10 10 05 p  m" src="https://user-images.githubusercontent.com/25566530/75639963-81c73a80-5c09-11ea-951d-47f6403d43a3.png">

**Comment by AladinWay** [comment]
I have updated the code example to the latest version of Alamofire
