### ISSUE TITLE
Problem in sending Query and Field parameters

### ISSUE THREAD

**Issue by Asad4429** [AladinWay/NetworkingExample#7]
How to send query parameters and field parameters in URL request?

**Comment by AladinWay** [comment]
As you can see in https://github.com/AladinWay/NetworkingExample/blob/e0279ea5268c2b98c3c01f50197733dafe27fe2e/Networking/APIClient/APIRouter.swift#L62 we are assuming that paranmeters are the body HTTP parameters of the requests but you can change the `APIRouter.swift` from having only `private var parameters: Parameters?` to having two variables one `private var queryParameters: Parameters?` and the other `private var queryParameters: Parameters?` and then add those parameters to the `URLRequest` in here https://github.com/AladinWay/NetworkingExample/blob/e0279ea5268c2b98c3c01f50197733dafe27fe2e/Networking/APIClient/APIRouter.swift#L50
