### ISSUE TITLE
Simple POST with Headers Error

### ISSUE THREAD

**Issue by gbattiston** [AladinWay/NetworkingExample#8]
Hey man, how are you?

I'm trying to make a simple post sending some headers, the servers hits an error 400 but the response shows as success, which is really odd.

This is the code I'm using in my APIClient:

     private static func performRequest<T: Codable>(route: APIConfiguration, decoder: JSONDecoder = JSONDecoder(), completion:@escaping (Result<T>)->Void) -> DataRequest {
        return AF.request(route).responseJSONDecodable(decoder: decoder) {
            (response: DataResponse<T>) in completion(response.result)
        }
    }

    static func postUser(completion:@escaping (Result<BaseResult>) -> Void) {
        let jsonDecoder: JSONDecoder = JSONDecoder()
        jsonDecoder.dateDecodingStrategy = .formatted(.complexesDateFormatter)
        performRequest(route: UserEndpoint.postUser(), decoder: jsonDecoder, completion: completion)
    }

What I'm trying to do is not having to pass a "BaseResult":

```
      struct BaseResult: Codable {
         var code: Int?
      }
```

This is UserEndpoint:
 
    func asURLRequest() throws -> URLRequest {
        let url: URL = try K.ProductionServer.baseURL.asURL()
        
        var urlRequest: URLRequest = URLRequest(url: url.appendingPathComponent(path))
        
        // HTTP Method
        urlRequest.httpMethod = method.rawValue
        
        let token: String = UserDefaults.standard.string(forKey: "Token") ?? ""
        let bearerToken: String = "Bearer " + token
        let bundleId: String = Bundle.footballNow.bundleIdentifier!
        
        // Common Headers
        urlRequest.setValue(ContentType.json.rawValue, forHTTPHeaderField: HTTPHeaderField.acceptType.rawValue)
        urlRequest.setValue(ContentType.json.rawValue, forHTTPHeaderField: HTTPHeaderField.contentType.rawValue)
        urlRequest.setValue(bearerToken, forHTTPHeaderField: HTTPHeaderField.authentication.rawValue)
        urlRequest.setValue(bundleId, forHTTPHeaderField: HTTPHeaderField.bundleIdentifier.rawValue)
        
        return urlRequest
    } 

Any thoughts?
Thanks

**Comment by AladinWay** [comment]
You need to use `validate()`  like : 

`return AF.request(route).validate().responseJSONDecodable(decoder: decoder)`

https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#response-validation
